project:
  type: book
  output-dir: docs

book:
  title: "Tips & tRicks in R"
  author: "Amanda D. Perez, PhD"
  date-meta: today
  reader-mode: true
  page-footer:
    left: |
      This document was put together with Amanda D. Perez to create a single resource hosting code she regularly uses.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - intro.qmd

    - part: data-exploration.qmd
      chapters:
        - psych.qmd
        - tidyverse.qmd


format:
  html:
    theme:
      - cosmo
      - style.scss
    cover-image: cover.png
    code-link: true
    callout-appearance: simple
    number-sections: true
  pdf:
    documentclass: scrreprt
    number-sections: true



